# Generated by Django 3.2.9 on 2021-12-05 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_books',
            name='isbn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d\\d-\\d\\d-\\d\\d-\\d\\d$')]),
        ),
    ]
