# Generated by Django 3.2.9 on 2021-12-05 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_external_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_books',
            name='isbn',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d\\d-\\d\\d-\\d\\d-\\d\\d$')]),
        ),
    ]
